version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data



  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_MANAGEMENT_LISTENER=0.0.0.0:15672
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=strongpassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq-data:/bitnami/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  transaction-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DSN: "postgresql://user:password@postgres/transactions"
      RABBITMQ_URI: "amqp://user:password@rabbitmq:5672"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres-data:
  rabbitmq-data:
