global:
  scrape_interval: 5s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']