global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
      
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8002']

  - job_name: 'worker0'
    static_configs:
      - targets: ['worker0:8001']

  - job_name: 'worker1'
    static_configs:
      - targets: ['worker1:8001']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
